### ISSUE TITLE
polycat module simply won't work (???)

### ISSUE THREAD

**Issue by falcie1337** [2IMT/polycat#3]
idk what i'm doing wrong here i literally did every single step like what the readme says and it just won't work lol

**Comment by 2IMT** [comment]
Does it work when you open it from terminal?

**Comment by falcie1337** [comment]
> Does it work when you open it from terminal?

it runs the cat animation indefinitely on my terminal until i close it, but when i put the module on polybar it simply refuses to show up there

**Comment by 2IMT** [comment]
> > Does it work when you open it from terminal?
> 
> it runs the cat animation indefinitely on my terminal until i close it, but when i put the module on polybar it simply refuses to show up there

Can you show your polybar config?

**Comment by falcie1337** [comment]
> > > Does it work when you open it from terminal?
> > 
> > 
> > it runs the cat animation indefinitely on my terminal until i close it, but when i put the module on polybar it simply refuses to show up there
> 
> Can you show your polybar config?

alright, here it is:
`[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/bar]
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "FiraMono Nerd Font:size=11:;2"
;font-1 = "polycat"

modules-left = xworkspaces xwindow
modules-right = pulseaudio memory polycat xkeyboard systray date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 4pt
tray-spacing = 8pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/polycat]
type = custom/polycat
exec = /home/falcie/Downloads/polycat/polycat
tail = true

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰑭 "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
`

**Comment by 2IMT** [comment]
> > > > Does it work when you open it from terminal?
> > > 
> > > 
> > > it runs the cat animation indefinitely on my terminal until i close it, but when i put the module on polybar it simply refuses to show up there
> > 
> > Can you show your polybar config?
> 
> alright, here it is:
> ```[colors]
> background = #282A2E
> background-alt = #373B41
> foreground = #C5C8C6
> primary = #F0C674
> secondary = #8ABEB7
> alert = #A54242
> disabled = #707880
> 
> [bar/bar]
> width = 100%
> height = 24pt
> radius = 6
> 
> ; dpi = 96
> 
> background = ${colors.background}
> foreground = ${colors.foreground}
> 
> line-size = 3pt
> 
> border-size = 4pt
> border-color = #00000000
> 
> padding-left = 0
> padding-right = 1
> 
> module-margin = 1
> 
> separator = |
> separator-foreground = ${colors.disabled}
> 
> font-0 = "FiraMono Nerd Font:size=11:;2"
> font-1 = "polycat"
> 
> modules-left = xworkspaces xwindow
> modules-right = pulseaudio memory polycat xkeyboard systray date
> 
> cursor-click = pointer
> cursor-scroll = ns-resize
> 
> enable-ipc = true
> 
> ; wm-restack = generic
> ; wm-restack = bspwm
> wm-restack = i3
> 
> ; override-redirect = true
> 
> [module/systray]
> type = internal/tray
> 
> format-margin = 4pt
> tray-spacing = 8pt
> 
> [module/xworkspaces]
> type = internal/xworkspaces
> 
> label-active = %name%
> label-active-background = ${colors.background-alt}
> label-active-underline= ${colors.primary}
> label-active-padding = 1
> 
> label-occupied = %name%
> label-occupied-padding = 1
> 
> label-urgent = %name%
> label-urgent-background = ${colors.alert}
> label-urgent-padding = 1
> 
> label-empty = %name%
> label-empty-foreground = ${colors.disabled}
> label-empty-padding = 1
> 
> [module/xwindow]
> type = internal/xwindow
> label = %title:0:60:...%
> 
> [module/filesystem]
> type = internal/fs
> interval = 25
> 
> mount-0 = /
> 
> label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
> 
> label-unmounted = %mountpoint% not mounted
> label-unmounted-foreground = ${colors.disabled}
> 
> [module/polycat]
> type = custom/polycat
> exec = /home/falcie/Downloads/polycat/polycat
> tail = true
> 
> [module/pulseaudio]
> type = internal/pulseaudio
> 
> format-volume-prefix = "󰕾 "
> format-volume-prefix-foreground = ${colors.primary}
> format-volume = <label-volume>
> 
> label-volume = %percentage%%
> 
> label-muted = muted
> label-muted-foreground = ${colors.disabled}
> 
> [module/xkeyboard]
> type = internal/xkeyboard
> blacklist-0 = num lock
> 
> label-layout = %layout%
> label-layout-foreground = ${colors.primary}
> 
> label-indicator-padding = 2
> label-indicator-margin = 1
> label-indicator-foreground = ${colors.background}
> label-indicator-background = ${colors.secondary}
> 
> [module/memory]
> type = internal/memory
> interval = 2
> format-prefix = "󰑭 "
> format-prefix-foreground = ${colors.primary}
> label = %percentage_used:2%%
> 
> [module/cpu]
> type = internal/cpu
> interval = 2
> format-prefix = " "
> format-prefix-foreground = ${colors.primary}
> label = %percentage:2%%
> 
> [network-base]
> type = internal/network
> interval = 5
> format-connected = <label-connected>
> format-disconnected = <label-disconnected>
> label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
> 
> [module/wlan]
> inherit = network-base
> interface-type = wireless
> label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%
> 
> [module/eth]
> inherit = network-base
> interface-type = wired
> label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%
> 
> [module/date]
> type = internal/date
> interval = 1
> 
> date = %Y-%m-%d %H:%M:%S
> 
> label = %date%
> label-foreground = ${colors.primary}
> 
> [settings]
> screenchange-reload = true
> pseudo-transparency = true
> 
> ; vim:ft=dosini
> ```

Looks fine to me. Make sure the path to the executable is valid and the font is properly installed in your system.

**Comment by falcie1337** [comment]
i'll try moving the polycat executable to some other place, let me check if it works real quick

**Comment by falcie1337** [comment]
i tried changing it to my /.local/bin/ directory since it is in my fish path but it didn't seem to change much, still got nothing

> i'll try moving the polycat executable to some other place, let me check if it works real quick

**Comment by 2IMT** [comment]
Check polybar's console output. Try starting it from your terminal. These logs could contain useful information to resolve the issue

**Comment by falcie1337** [comment]
```polybar|notice:  Parsing config file: /home/falcie/.config/polybar/config.ini
polybar|notice:  Listening for IPC messages (PID: 595673)
polybar|notice:  Loading module 'xworkspaces' of type 'internal/xworkspaces'
polybar|notice:  Loading module 'xwindow' of type 'internal/xwindow'
polybar|notice:  Loading module 'pulseaudio' of type 'internal/pulseaudio'
polybar|notice:  pulseaudio: using default sink alsa_output.pci-0000_08_00.6.analog-stereo
polybar|notice:  Loading module 'memory' of type 'internal/memory'
polybar|notice:  Loading module 'polycat' of type 'custom/polycat'
polybar|error: Disabling module "polycat" (reason: Unknown module: custom/polycat)
polybar|notice:  Loading module 'xkeyboard' of type 'internal/xkeyboard'
polybar|notice:  Loading module 'systray' of type 'internal/tray'
polybar|notice:  Loading module 'date' of type 'internal/date'
polybar|notice:  Loaded 7 modules
polybar|notice:  Loaded font "FiraMono Nerd Font:size=11:" (name=FiraMono Nerd Font, offset=2, file=/usr/local/share/fonts/f/FiraMonoNerdFont_Regular.otf)
polybar|notice:  Loaded font "polycat" (name=polycat, offset=0, file=/home/falcie/.local/share/fonts/Unknown Vendor/TrueType/polycat/polycat_Regular.ttf)
polybar|warn:  Ignoring restack of i3 window (not needed when `override-redirect = false`)
```

> Check polybar's console output. Try starting it from your terminal. These logs could contain useful information to resolve the issue

It apparently doesn't recognize polycat as a module and automatically disables it???

**Comment by 2IMT** [comment]
Apologies, it's actually a mistake in README.md
Under the line `[custom/polycat]`, the `type` key should be equal to `custom/script`, not to `custom/polycat`

**Comment by falcie1337** [comment]
yay, now it works! thank you for going through this with me :)

**Comment by falcie1337** [comment]
btw, last thing i will ask here, is there any easy way to change the foreground of the polycat module? or is it just not possible? thank you in advance, i will still use it even if there isn't any way to do it lol
